apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      # Sécurité au niveau du Pod (Seccomp et NonRoot)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: echoserver
          # On utilise une image plus récente et sécurisée (nginxinc/nginx-unprivileged)
          # car l'ancien echoserver tente de tourner en root (port 80)
          image: nginxinc/nginx-unprivileged:stable-alpine
          ports:
            - containerPort: 8080
          # Sécurité au niveau du Conteneur (Privilèges et Capabilities)
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          # Obligatoire quand readOnlyRootFilesystem est true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}