apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world-tools
  namespace: flux-system
spec:
  targetNamespace: hello-world-tools
  interval: 10m
  path: "./apps/hello-world"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - target:
        kind: HelmRelease
        name: podinfo-hello
      patch: |
        - op: replace
          path: /spec/values/ui/message
          value: "<h1>Hello from Cluster Tools</h1>"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-tools