apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-hello-world
  namespace: hello-world
spec:
  interval: 10m
  releaseName: podinfo
  targetNamespace: hello-world
  chart:
    spec:
      chart: podinfo
      version: "6.6.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    ui:
      message: "Mon Hello World via Flux et Cilium !"
      color: "#345ecf"
    replicaCount: 1
  install:
    createNamespace: true