apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weavework-hr
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/gitops-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  values:
    image:
      tag: v0.38.0
    deployment:
      additionalContainers: [ ] # Gardez-le si déjà présent
      securityContext:
        capabilities:
          drop:
            - NET_RAW
    adminUser:
      create: true
      passwordHash: $2a$12$XStXAMW19LmvcT3sDOdaEOw9r4IhpZoZIkhBKr6HYUEJdKaTPsqHy
      username: admin
    service:
      port: 9001
      targetPort: 9001
      type: ClusterIP