apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller # Optionnel: à ajouter si vous gérez des images
    - image-automation-controller # Optionnel: à ajouter pour l'auto-commit
  cluster:
    type: kubernetes
    size: medium
    multitenant: false
    networkPolicy: true
    domain: "cluster.local" # Valeur standard pour la majorité des clusters K8s
  sync:
    kind: GitRepository
    url: "https://github.com/yuanzhaoy/fluxcd-repo.git"
    ref: "refs/heads/main"
    path: "./clusters/sbx/tools"
    pullSecret: "flux-system"
